### ISSUE TITLE
Slashing.signing_info_by_address doesn't behave as expected

### ISSUE THREAD

**Issue by etienne-napoleone** [terra-project/jigu#5]
* Jigu version: 0.1.2
* Python version: 3.7.7
* Operating System: macOS Mojave 10.14.6 (18G3020)

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

list all signing info as indicated [here](https://jigu.terra.money/docs/modules/slashing.html#signing-info).

### What I Did

```
>>> from jigu import Terra
>>> terra = Terra("columbus-3", "https://lcd.terra.dev")
>>> terra.is_connected()
True
>>> terra.slashing.signing_info_by_address()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/valmailer-tZO3ahg3-py3.7/lib/python3.7/site-packages/jigu/client/lcd/api/modules/slashing.py", line 36, in signing_info_by_address
    validate_val_consaddress(address)
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/valmailer-tZO3ahg3-py3.7/lib/python3.7/site-packages/jigu/util/validation.py", line 84, in validate_val_consaddress
    if not is_val_consaddress(data):
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/valmailer-tZO3ahg3-py3.7/lib/python3.7/site-packages/jigu/util/validation.py", line 45, in is_val_consaddress
    is_bech32(data)
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/valmailer-tZO3ahg3-py3.7/lib/python3.7/site-packages/jigu/util/validation.py", line 20, in is_bech32
    return bech32.bech32_decode(data) != (None, None,)
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/valmailer-tZO3ahg3-py3.7/lib/python3.7/site-packages/bech32/__init__.py", line 66, in bech32_decode
    if (any(ord(x) < 33 or ord(x) > 126 for x in bech)) or (
TypeError: 'NoneType' object is not iterable
```

**Comment by ouiliame** [comment]
Fixed in v0.1.4.
